stages:
  - test
  - test-report
  - deploy

run-tests:
  stage: test
  image: ubuntu:24.04
  allow_failure: true

  variables:
    APP_HOST: "http://localhost:8000"
    DATABASE_URL: "sqlite+aiosqlite:///./local.db"
    JWT_ALGORITHM: "HS256"
    JWT_SECRET_KEY: "qa-automation-engineer-api-course-secret-key"
    JWT_ACCESS_TOKEN_EXPIRE: 1800
    JWT_REFRESH_TOKEN_EXPIRE: 5184000

  before_script:
    - apt-get update
    - apt-get install -y python3.12 python3.12-venv python3-pip git

    - python3.12 -m venv venv
    - source venv/bin/activate

    - pip install -r requirements.txt

  script:
    - git clone https://github.com/Nikita-Filonov/qa-automation-engineer-api-course.git

    - pip install -r qa-automation-engineer-api-course/requirements.txt

    - uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir ./qa-automation-engineer-api-course &
    - sleep 3

    - pytest -m regression --alluredir=allure-results --numprocesses 2

  artifacts:
    paths:
      - allure-results/
    expire_in: 7 days
    when: always

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

publish-report:
    stage: test-report
    image: ubuntu:24.04
    allow_failure: true

    before_script:
      - apt-get update
      - apt-get install -y openjdk-11-jre wget tar

      - wget https://github.com/allure-framework/allure2/releases/download/2.38.0/allure-2.38.0.tgz
      - tar -xvf allure-2.38.0.tgz

    script:
      - allure-2.38.0/bin/allure generate allure-results -o allure-report --clean

    needs: [ "run-tests" ]

    artifacts:
      paths:
        - allure-report/
      expire_in: 7 days
      when: always

    rules:
      - if: '$CI_COMMIT_BRANCH == "main"'

pages:
  stage: deploy

  script:
    - mkdir -p public
    - cp -r allure-report/* public/

  artifacts:
    paths:
      - public

  needs: [ "publish-report" ]

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

